"""add grade points

Revision ID: 5492126dbd51
Revises: 5a2e16422b0f
Create Date: 2026-06-19 12:18:42.789009
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401 — SQLModel column types referenced in autogenerated ops
from alembic import op


revision: str = '5492126dbd51'
down_revision: str | None = '5a2e16422b0f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'grade', sa.Column('points', sa.Integer(), nullable=False, server_default='0')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grade', 'points')
    # ### end Alembic commands ###
