"""fixture provider-scoped uniqueness

Revision ID: 5a2e16422b0f
Revises: 5fefeeae33e9
Create Date: 2026-06-19 08:20:15.951953
"""
from collections.abc import Sequence

import sqlmodel  # noqa: F401 — SQLModel column types referenced in autogenerated ops
from alembic import op

revision: str = '5a2e16422b0f'
down_revision: str | None = '5fefeeae33e9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fixture_external_id'), table_name='fixture')
    op.create_index(op.f('ix_fixture_external_id'), 'fixture', ['external_id'], unique=False)
    op.create_index(op.f('ix_fixture_provider'), 'fixture', ['provider'], unique=False)
    op.create_unique_constraint('uq_fixture_provider_external', 'fixture', ['provider', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_fixture_provider_external', 'fixture', type_='unique')
    op.drop_index(op.f('ix_fixture_provider'), table_name='fixture')
    op.drop_index(op.f('ix_fixture_external_id'), table_name='fixture')
    op.create_index(op.f('ix_fixture_external_id'), 'fixture', ['external_id'], unique=True)
    # ### end Alembic commands ###
