"""initial schema

Revision ID: 5fefeeae33e9
Revises: 
Create Date: 2026-06-19 08:06:39.757439
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401 — SQLModel column types referenced in autogenerated ops
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '5fefeeae33e9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibrationprofile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('n_graded', sa.Integer(), nullable=False),
    sa.Column('metric_aggregates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bias_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_snippet', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibrationprofile_version'), 'calibrationprofile', ['version'], unique=True)
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_window_hours', sa.Integer(), nullable=False),
    sa.Column('cadence', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('per_run_fixture_cap', sa.Integer(), nullable=False),
    sa.Column('spend_cap', sa.Float(), nullable=False),
    sa.Column('use_odds', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trigger', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('totals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_started_at'), 'run', ['started_at'], unique=False)
    op.create_index(op.f('ix_run_status'), 'run', ['status'], unique=False)
    op.create_index(op.f('ix_run_type'), 'run', ['type'], unique=False)
    op.create_table('team',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fifa_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('crest_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_fifa_code'), 'team', ['fifa_code'], unique=True)
    op.create_table('fixture',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('home_team_id', sa.Uuid(), nullable=False),
    sa.Column('away_team_id', sa.Uuid(), nullable=False),
    sa.Column('kickoff_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('venue', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixture_away_team_id'), 'fixture', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_fixture_external_id'), 'fixture', ['external_id'], unique=True)
    op.create_index(op.f('ix_fixture_home_team_id'), 'fixture', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_fixture_kickoff_utc'), 'fixture', ['kickoff_utc'], unique=False)
    op.create_index(op.f('ix_fixture_status'), 'fixture', ['status'], unique=False)
    op.create_table('player',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('external_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_name'), 'player', ['name'], unique=False)
    op.create_index(op.f('ix_player_team_id'), 'player', ['team_id'], unique=False)
    op.create_table('datasnapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fixture_id', sa.Uuid(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('search_queries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_quality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('missing_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixture.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasnapshot_fixture_id'), 'datasnapshot', ['fixture_id'], unique=False)
    op.create_table('result',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fixture_id', sa.Uuid(), nullable=False),
    sa.Column('home_score_90', sa.Integer(), nullable=False),
    sa.Column('away_score_90', sa.Integer(), nullable=False),
    sa.Column('ft_outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decided_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('advanced_team_id', sa.Uuid(), nullable=True),
    sa.Column('scorers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['advanced_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixture.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_result_fixture_id'), 'result', ['fixture_id'], unique=True)
    op.create_table('runitem',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('fixture_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('spend_estimate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixture.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runitem_fixture_id'), 'runitem', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_runitem_run_id'), 'runitem', ['run_id'], unique=False)
    op.create_table('prediction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fixture_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('scorers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.Column('advancing_team_id', sa.Uuid(), nullable=True),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schema_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('calibration_version', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('failure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_output', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['advancing_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixture.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['datasnapshot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id', 'prompt_version', 'model_id', 'calibration_version', name='uq_prediction_version')
    )
    op.create_index(op.f('ix_prediction_created_at'), 'prediction', ['created_at'], unique=False)
    op.create_index(op.f('ix_prediction_fixture_id'), 'prediction', ['fixture_id'], unique=False)
    op.create_table('grade',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prediction_id', sa.Uuid(), nullable=False),
    sa.Column('fixture_id', sa.Uuid(), nullable=False),
    sa.Column('exact_hit', sa.Boolean(), nullable=False),
    sa.Column('outcome_correct', sa.Boolean(), nullable=False),
    sa.Column('goals_abs_error', sa.Integer(), nullable=False),
    sa.Column('scorer_precision', sa.Float(), nullable=False),
    sa.Column('scorer_recall', sa.Float(), nullable=False),
    sa.Column('scorer_brier', sa.Float(), nullable=False),
    sa.Column('confidence_brier', sa.Float(), nullable=False),
    sa.Column('advancing_correct', sa.Boolean(), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixture.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['prediction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grade_fixture_id'), 'grade', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_grade_prediction_id'), 'grade', ['prediction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grade_prediction_id'), table_name='grade')
    op.drop_index(op.f('ix_grade_fixture_id'), table_name='grade')
    op.drop_table('grade')
    op.drop_index(op.f('ix_prediction_fixture_id'), table_name='prediction')
    op.drop_index(op.f('ix_prediction_created_at'), table_name='prediction')
    op.drop_table('prediction')
    op.drop_index(op.f('ix_runitem_run_id'), table_name='runitem')
    op.drop_index(op.f('ix_runitem_fixture_id'), table_name='runitem')
    op.drop_table('runitem')
    op.drop_index(op.f('ix_result_fixture_id'), table_name='result')
    op.drop_table('result')
    op.drop_index(op.f('ix_datasnapshot_fixture_id'), table_name='datasnapshot')
    op.drop_table('datasnapshot')
    op.drop_index(op.f('ix_player_team_id'), table_name='player')
    op.drop_index(op.f('ix_player_name'), table_name='player')
    op.drop_table('player')
    op.drop_index(op.f('ix_fixture_status'), table_name='fixture')
    op.drop_index(op.f('ix_fixture_kickoff_utc'), table_name='fixture')
    op.drop_index(op.f('ix_fixture_home_team_id'), table_name='fixture')
    op.drop_index(op.f('ix_fixture_external_id'), table_name='fixture')
    op.drop_index(op.f('ix_fixture_away_team_id'), table_name='fixture')
    op.drop_table('fixture')
    op.drop_index(op.f('ix_team_fifa_code'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_run_type'), table_name='run')
    op.drop_index(op.f('ix_run_status'), table_name='run')
    op.drop_index(op.f('ix_run_started_at'), table_name='run')
    op.drop_table('run')
    op.drop_table('config')
    op.drop_index(op.f('ix_calibrationprofile_version'), table_name='calibrationprofile')
    op.drop_table('calibrationprofile')
    # ### end Alembic commands ###
